"use server";

import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { StreamClient } from "@stream-io/node-sdk";

/**
 * Generates a Stream.io JWT token for the authenticated user
 * 
 * This function:
 * 1. Verifies user is authenticated (via Better Auth)
 * 2. Creates Stream server client with secret key
 * 3. Generates JWT token for the user
 * 4. Returns token to client
 * 
 * @returns {Promise<string>} JWT token string
 * @throws {Error} If user is not authenticated
 */
export const streamTokenProvider = async (): Promise<string> => {
  try {
    // Step 1: Get authenticated user from Better Auth
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session?.user?.id) {
      console.error("Token generation failed: User not authenticated");
      throw new Error("User not authenticated");
    }

    // Step 2: Verify environment variables
    const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY;
    const secretKey = process.env.STREAM_SECRET_KEY || process.env.STREAM_API_SECRET;

    if (!apiKey || !secretKey) {
      console.error("Token generation failed: Missing Stream.io credentials");
      throw new Error("Stream.io credentials not configured");
    }

    // Step 3: Initialize Stream server client
    // This client is used server-side only with the secret key
    const streamClient = new StreamClient(apiKey, secretKey);

    // Step 4: Generate JWT token for this user
    // The token includes:
    // - user_id: User ID from Better Auth
    // - iat: issued at timestamp (auto-generated by SDK)
    // - exp: expiration timestamp (default 1 hour, auto-generated by SDK)
    // Note: generateUserToken expects a payload object with user_id property
    const userId = String(session.user.id); // Ensure it's a string
    
    if (!userId || userId.trim() === '') {
      throw new Error("Invalid user ID for token generation");
    }
    
    // Create payload object - must be a plain object, not a string
    const payload: { user_id: string } = { user_id: userId };
    
    // Double-check payload is correct type
    if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) {
      throw new Error(`Invalid payload type: ${typeof payload}`);
    }
    
    if (typeof payload.user_id !== 'string') {
      throw new Error(`Invalid user_id type: ${typeof payload.user_id}`);
    }
    
    console.log("Generating token with payload:", { user_id: payload.user_id });
    const token = streamClient.generateUserToken(payload);

    if (!token) {
      throw new Error("Failed to generate token");
    }

    console.log(`Token generated successfully for user: ${session.user.id}`);
    return token;
  } catch (error) {
    console.error("Token generation error:", error);
    // Re-throw to let Stream SDK handle it
    // SDK will retry token generation automatically
    throw error;
  }
};

